name: Tests

on: [push, pull_request]

jobs:
    tests:
        name: Tests PHP ${{ matrix.php }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                php: [8.0, 8.1]

        services:
            neo4j:
                image: neo4j:4.4
                env:
                  NEO4J_AUTH: neo4j/test
                ports:
                  - 7687:7687
                  - 7474:7474
                options: >-
                  --health-cmd "wget http://localhost:7474 || exit 1"

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - uses: php-actions/composer@v6
              with:
                  progress: yes
                  php_version: 8.0
                  version: 2

            - name: Static analysis
              run: vendor/bin/phpstan

            - name: Tests
              run: vendor/bin/phpunit

